'use strict';

module.exports = {

  buttons: [{
    code: 116,
    label: 'ON/OFF',
    icon: 'power_settings_new'
  }, {
    code: 512,
    label: '0'
  }, {
    code: 513,
    label: '1'
  }, {
    code: 514,
    label: '2'
  }, {
    code: 515,
    label: '3'
  }, {
    code: 516,
    label: '4'
  }, {
    code: 517,
    label: '5'
  }, {
    code: 518,
    label: '6'
  }, {
    code: 519,
    label: '7'
  }, {
    code: 520,
    label: '8'
  }, {
    code: 521,
    label: '9'
  }, {
    code: 402,
    label: 'CH+',
    icon: 'add_to_queue'
  }, {
    code: 403,
    label: 'CH-',
    icon: 'remove_from_queue'
  }, {
    code: 115,
    label: 'VOL+',
    icon: 'volume_up'
  }, {
    code: 114,
    label: 'VOL-',
    icon: 'volume_down'
  }, {
    code: 113,
    label: 'MUTE',
    icon: 'volume_mute'
  }, {
    code: 103,
    label: 'UP',
    icon: 'keyboard_arrow_up'
  }, {
    code: 108,
    label: 'DOWN',
    icon: 'keyboard_arrow_down'
  }, {
    code: 105,
    label: 'LEFT',
    icon: 'keyboard_arrow_left'
  }, {
    code: 106,
    label: 'RIGHT',
    icon: 'keyboard_arrow_right'
  }, {
    code: 352,
    label: 'OK'
  }, {
    code: 158,
    label: 'BACK',
    icon: 'keyboard_return'
  }, {
    code: 139,
    label: 'MENU',
    icon: 'menu'
  }, {
    code: 164,
    label: 'PLAY/PAUSE',
    icon: 'play_arrow'
  }, {
    code: 168,
    label: 'FBWD',
    icon: 'fast_rewind'
  }, {
    code: 159,
    label: 'FFWD',
    icon: 'fast_forward'
  }, {
    code: 167,
    label: 'REC',
    icon: 'fiber_manual_record'
  }, {
    code: 393,
    label: 'VOD'
  }]
};